services:
  autoindex:
    build: .
    image: autoindex
    restart: unless-stopped
    ports:
      - "5555:8080"
    volumes:
      - /volume1/nginx/files:/data:ro # change to the directory you want to serve
    command: ["-tree"]        # extra flags, e.g. -tree or -all
