services:
  autoindex:
    build: .
    image: autoindex
    restart: unless-stopped
    ports:
      - "5555:8080"
    volumes:
      - /volume1/nginx/files:/data:ro
    command: ["-tree", "-hostname", "naxx"]
